// <auto-generated />
using BerberKuafor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BerberKuafor.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241228071745_birinci")]
    partial class birinci
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BerberKuafor.Models.Musteri", b =>
                {
                    b.Property<int>("IdMusteri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMusteri"));

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personIDPersonel")
                        .HasColumnType("int");

                    b.HasKey("IdMusteri");

                    b.HasIndex("personIDPersonel");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("BerberKuafor.Models.Personel", b =>
                {
                    b.Property<int>("IDPersonel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPersonel"));

                    b.Property<string>("PersonelAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDPersonel");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("BerberKuafor.Models.Musteri", b =>
                {
                    b.HasOne("BerberKuafor.Models.Personel", "person")
                        .WithMany("Musteriler")
                        .HasForeignKey("personIDPersonel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("BerberKuafor.Models.Personel", b =>
                {
                    b.Navigation("Musteriler");
                });
#pragma warning restore 612, 618
        }
    }
}
